[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[project]
name = "sim_toolkit"           # what appears on PyPI / pip install name
version = "4.0.0"
description = "Synthetic Images Metrics Toolkit (SIM Toolkit)"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "NPOSL-3.0" }
authors = [{ name = "Matteo Lai", email = "matteo.lai3@unibo.it" }]
keywords = ["generative", "synthetic images", "images", "metrics", "validation", "medical-imaging"]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Image Processing",
]

# == Core dependencies ==
dependencies = [
    "numpy>=1.23,<1.24",
    "scipy>=1.15",
    "scikit-learn>=1.0,<1.3",
    "tqdm>=4.64",
    "matplotlib>=3.5,<3.8",
    "seaborn>=0.13",
    "reportlab>=4.0",
    "pillow>=9.0",
    "click>=8.1",
    "requests>=2.24",
    "imageio-ffmpeg>=0.4.3",
    "psutil>=5.7",
    "pyspng>=0.1.1",
]

[project.optional-dependencies]
# PyTorch backend
torch = [
  "torch>=2.1",
  "torchvision>=0.16",
]

# TensorFlow backend
tf = [
  "protobuf>=3.20,<4.0",
  "keras>=2.12,<2.13",
  "tensorflow>=2.12,<2.13; platform_machine == 'x86_64' and sys_platform != 'darwin'",
  "tensorflow>=2.12,<2.13; platform_machine == 'AMD64' and sys_platform == 'win32'",
  "tensorflow-macos>=2.12,<2.13; sys_platform == 'darwin' and platform_machine == 'arm64'",
]

# File formats / datasets
nifti  = ["nibabel>=5.0"]
tiff   = ["tifffile>=2023.2.3", "imagecodecs>=2023.1.23; platform_system!='Windows'"]
csv    = ["pandas>=1.5"]
opencv = ["opencv-python>=4.8"]
dicom  = ["pydicom"]

# Dev / CI / docs
dev = [
  "pytest>=7.0",
  "pytest-cov>=4.1",
  "ruff>=0.5",
  "mypy>=1.8",
  "build>=1.0",
  "twine>=5.0",
  "mkdocs-material>=9.5"
]

[tool.hatch.build.targets.wheel]
packages = ["sim_toolkit"]
include = ["LICENSES/**"]

[tool.hatch.build.targets.sdist]
include = ["sim_toolkit", "README.md", "LICENSES/**"]